### PR TITLE
New workflow: Pull Request Commenter

### PR DESCRIPTION
**Pull request by clifff**
## What

Adds a new workflow that will comment once on pull requests matching certain criteria with a custom message.

## Why

Emperor Penguin has several workflows that uses the `ethanis/nitpicker@v1` action to accomplish this task, but it fails intermittently with `Error: Not Found` errors.

Turns out commenting on PRs is relatively straight forward with `actions/github-script@v6` and we don't use the 'blocking' functionality that adds complexity to the other action, so figured a near drop in replacement would be a good way to fix those errors.

## Testing

Almost certainly a better way to do this than my 'do it live' approach, but tested this workflow in https://github.com/ArcadiaPower/fei-actions/pull/1

### CODE REVIEW

**Review by itsjoekent — APPROVED** [review]
Woo! Love to see new actions getting added here. actions/github-script seems super useful, TIL

**Review by arapoport3 — APPROVED** [review]
Very neat! do we have the ability to user internal actions set up now?

**Comment by itsjoekent** [comment]
@arapoport3 Due to limitations with Github, this repo has to be public (*there are a lot of angry comments across the internet from paid Github accounts about this, and it seems like self-hosted GH enterprise supports private reusable actions, so maybe one day this is better for everyone). Since it's public, I'm cautious about _what_ gets put in here, but as long as it's nothing super sensitive, it should be fine! 😅 

I also told Cliff, if we want we can also rename this repo to be more generic / not FEI specific.

**Comment by clifff** [comment]
I have not followed up on the internal repos thing. I enabled internal _packages_ the other day for @itsjoekent and thought that meant the plan had been sorted out, but I still don't see the options for internal repos so perhaps not

**Pull request merged**
